### ISSUE TITLE
OutOfRangeError (see above for traceback): RandomShuffleQueue

### ISSUE THREAD

**Issue by yongjin120** [leechanwoo/Tensorflow-projects#1]
Traceback (most recent call last):
  File "/data2/KYJ/tensorflow_youtube/cnn_example_prototype.py", line 79, in <module>
    sess.run(train)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: shuffle_batch = QueueDequeueMany[_class=["loc:@shuffle_batch/random_shuffle_queue"], component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

Caused by op u'shuffle_batch', defined at:
  File "/data2/KYJ/tensorflow_youtube/cnn_example_prototype.py", line 35, in <module>
    min_after_dequeue=100)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 917, in shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1099, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[Node: shuffle_batch = QueueDequeueMany[_class=["loc:@shuffle_batch/random_shuffle_queue"], component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

동일한 Dataset을 가지고 실행했을 때  위와 같은 오류가 발생합니다. 
구글에서 OutOfRangeError관련 에러를 찾아봐도 명확한 답이 안나와있습니다.  

혹시 gpu가 없으면 실행이 안되는건가 궁금합니다.

**Comment by kordokrip** [comment]
데이터 파이프라인 확인 : 입력 파이프라인에 충분한 데이터를 제공하고 있는지 확인하세요. 큐에 데이터를 공급하는 방법에 문제가 있을 수 있습니다.

대기열 작업 확인 : 데이터를 대기열에 넣는 방법, 대기열에서 빼는 방법 등 대기열과 관련된 작업을 다시 확인하세요. 대기열을 관리하는 방법에 실수가 없는지 확인하십시오.

데이터세트 크기 검사 : 데이터세트에 요청된 배치 크기를 충족할 만큼 충분한 요소가 있는지 확인하세요. 데이터 세트가 너무 작으면 이에 따라 배치 크기를 조정해야 할 수도 있습니다.

대기열 상태 확인 : 대기열이 조기에 닫히는지 또는 코드에서 대기열이 관리되는 방식에 문제가 있는지 확인합니다.

세션 관리 검토 : TensorFlow 세션을 올바르게 시작하고 닫고 있는지 확인하세요. 세션이 예기치 않게 닫히면 대기열 작업에 문제가 발생할 수 있습니다.
